-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- Clean up
drop table if exists public.projects;
drop table if exists public.skills;
drop table if exists public.profile;
drop table if exists public.socials;

-- Projects Table
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  tech_stack text[] not null, -- Matched to schema.ts
  project_url text,
  repo_url text, -- Matched to schema.ts (was github_url)
  image_url text,
  display_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.projects enable row level security;

create policy "Allow public read access on projects"
  on public.projects for select
  using (true);

create policy "Allow authenticated insert on projects"
  on public.projects for insert
  with check (auth.role() = 'authenticated');

create policy "Allow authenticated update on projects"
  on public.projects for update
  using (auth.role() = 'authenticated');

create policy "Allow authenticated delete on projects"
  on public.projects for delete
  using (auth.role() = 'authenticated');

-- Skills Table
create table public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null, -- icon/category
  proficiency integer default 100,
  visible boolean default true,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.skills enable row level security;

create policy "Allow public read access on skills"
  on public.skills for select
  using (true);

create policy "Allow authenticated insert on skills"
  on public.skills for insert
  with check (auth.role() = 'authenticated');

create policy "Allow authenticated update on skills"
  on public.skills for update
  using (auth.role() = 'authenticated');

create policy "Allow authenticated delete on skills"
  on public.skills for delete
  using (auth.role() = 'authenticated');

-- Profile Table (Singleton or per user, here treating as singleton portfolio profile)
create table public.profile (
  id bigint generated by default as identity primary key,
  name text not null,
  bio text not null,
  tagline text not null,
  avatar_url text,
  resume_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profile enable row level security;

create policy "Allow public read access on profile"
  on public.profile for select
  using (true);

create policy "Allow authenticated insert on profile"
  on public.profile for insert
  with check (auth.role() = 'authenticated');

create policy "Allow authenticated update on profile"
  on public.profile for update
  using (auth.role() = 'authenticated');

-- Socials Table (Contact Info)
create table public.socials (
  id bigint generated by default as identity primary key,
  platform text not null,
  url text not null,
  icon text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.socials enable row level security;

create policy "Allow public read access on socials"
  on public.socials for select
  using (true);

create policy "Allow authenticated mixed access on socials"
  on public.socials for all
  using (auth.role() = 'authenticated');

-- Storage Bucket for Images (Optional but good practice)
insert into storage.buckets (id, name, public) 
values ('portfolio', 'portfolio', true)
on conflict (id) do nothing;

create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'portfolio' );

create policy "Authenticated Insert"
  on storage.objects for insert
  with check ( bucket_id = 'portfolio' and auth.role() = 'authenticated' );
